[package]
name = "cowboy-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cowboy-core.workspace = true
async-trait.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tls-parser.workspace = true
httparse.workspace = true
hickory-proto.workspace = true

[dev-dependencies]
proptest.workspace = true
tokio-test.workspace = true
